### ISSUE TITLE
Not a bug report.

### ISSUE THREAD

**Issue by buggub** [lancelot1/ane-admob#1]
Just noticed your opened thread: https://github.com/Code-Alchemy/AdMobAne/issues/21
It is very ironic, the maintainer deleted all your texts. :)

In fact, I also highly doubt that project is a Trojan. And that is not the only doubtful projects on github.
I checked github's terms, unfortunately, there is no terms to prevent bad people uploading Trojans and viruses.

Could you provide the evidences of that project is a Trojan? I want to create a thread on some popular forums to describe this problem so that github will pay attention to it and fix it.

**Comment by valdiviaelmago** [comment]
@buggub CODE ALCHEMY'S ANE IS A TROJAN! DO NOT USE IT! IT STEALS 66% OF YOUR INCOME!!

Just decompile the ane's actionscript and you will see that 66% of your income is actually being stolen! (AdMobManager.as, Line 966)

YOU'RE LOSING MONEY IF YOU'RE USING IT!!!!
STAY AWAY FROM THIS ANE!

REFERENCES: 
- check out the last two posts on this official starling forum topic: http://forum.starling-framework.org/topic/codealchemys-admob-ane/page/2

SHAME ON YOU, CODE ALCHEMY!
