### ISSUE TITLE
Conflicting with Overlawled/GPS ane

### ISSUE THREAD

**Issue by WHAmarcelo** [lancelot1/ane-admob#6]
You said on news that is not conflicting anymore with GPS, but I've downloaded latest .ANE and when when I'm packing it appears the "dx tool failed" "AdRequest$ErrorCode" conflict when using it with https://github.com/overlawled/ANE-Google-Play-Game-Services

**Comment by nitacawo** [comment]
Hey nice to see that you updated your ane, It still conflicts with gps. For example with this one which I am currently using https://github.com/alextel69/google-play-game-services-ane
 Do you have any plans to do ane without gps?

**Comment by lancelot1** [comment]
Does google-play-game-services-ane have a version without gps?
